### PR TITLE
[Label Redesign] Fix match_vle_terminal_edge error

### PR DESCRIPTION
**Pull request by WendelLana**
Changed GRAPHOID to INT8OID (bigint) in age_vle and updated related regression tests (cypher_unwind, cypher_vle and cypher_with)

### CODE REVIEW

**Comment by mohayu22** [comment]
@WendelLana Regression tests are failing because of missing empty lines at the end of `cypher_unwind.out`, `cypher_with.out` and `cypher_vle.out`

```
--- /home/mohayu/Desktop/Rafsun/age/./regress/expected/cypher_unwind.out	2023-08-09 02:38:37.626680229 +0500
+++ /home/mohayu/Desktop/Rafsun/age/./regress/results/cypher_unwind.out	2023-08-09 02:42:02.726690883 +0500
@@ -214,4 +214,5 @@
  drop_graph 
 ------------
  
-(1 row)
\ No newline at end of file
+(1 row)
+

diff -U3 /home/mohayu/Desktop/Rafsun/age/./regress/expected/cypher_with.out /home/mohayu/Desktop/Rafsun/age/./regress/results/cypher_with.out
--- /home/mohayu/Desktop/Rafsun/age/./regress/expected/cypher_with.out	2023-08-09 02:40:31.350686137 +0500
+++ /home/mohayu/Desktop/Rafsun/age/./regress/results/cypher_with.out	2023-08-09 02:42:03.514690924 +0500
@@ -359,4 +359,4 @@
 
 --
 -- End of test
---
\ No newline at end of file
+--

diff -U3 /home/mohayu/Desktop/Rafsun/age/./regress/expected/cypher_vle.out /home/mohayu/Desktop/Rafsun/age/./regress/results/cypher_vle.out
--- /home/mohayu/Desktop/Rafsun/age/./regress/expected/cypher_vle.out	2023-08-09 02:40:50.822687148 +0500
+++ /home/mohayu/Desktop/Rafsun/age/./regress/results/cypher_vle.out	2023-08-09 02:42:05.318691018 +0500
@@ -1077,4 +1077,4 @@
 
 --
 -- End
---
\ No newline at end of file
+--
```

**Comment by rafsun42** [comment]
@mohayu22 Good catch. 

@WendelLana Please run `installcheck` before sending a PR. Ty.

**Comment by WendelLana** [comment]
@rafsun42 I've made `installcheck` before sending this PR. In my repository it's with all empty lines at the end of the files. It does not even show that I deleted this lines in the `Files changed` here, my screenshots:
image
image

**Comment by rafsun42** [comment]
@WendelLana Is it because you are using Windows terminal?

**Comment by WendelLana** [comment]
@rafsun42 I've fixed the issue and squashed the commits

**Comment by rafsun42** [comment]
@WendelLana Could you check whether the issue you fixed in age_vle.c also appears in other files?

**Comment by rafsun42** [comment]
@WendelLana No old commits from the previous label_redesign branch.

**Comment by WendelLana** [comment]
@rafsun42 This issue of `match_vle_terminal_edge` only occurs in age_vle.c file and I've done the rebase to latest label_redesign branch

**Pull request merged**
