### PR TITLE
Updated regression tests in cypher_call.out and cypher_union.out

### PR DESCRIPTION
**Pull request by mohayu22**
Changed regression tests in expected/cypher_call.out
and expected/cypher_union.out

### CODE REVIEW

**Comment by rafsun42** [comment]
@mohayu22 Could you please combine both of your PRs?

**Comment by mohayu22** [comment]
Ok

**Comment by mohayu22** [comment]
@rafsun42 Done

**Comment by rafsun42** [comment]
@mohayu22 You need to rebase your PR off label_redesign first.

**Pull request closed without merging**
